### ISSUE TITLE
[Feature] Add Regex to Library

### ISSUE THREAD

**Issue by jboetticher** [AmanRaj1608/create3#2]
(Moved from codebase TODO to an issue)

It would be nice if there was a function/tool option that allowed a user to input a regex match string as the vanity match instead of just looking for a prefix. 

Alternatively/additionally, it would be nice to have a function/option that allows for custom inputs for the salt. Such as finding a salt for the following: `keccack256(abi.encode(msg.sender, salt))`

**Comment by AmanRaj1608** [comment]
#1
